### ISSUE TITLE
CAN NOT  install

### ISSUE THREAD

**Issue by limuzisenlin** [IOBR/IOBR#10]
> if (!requireNamespace("IOBR", quietly = TRUE))
+     devtools::install_github("IOBR/IOBR",ref="master")
Downloading GitHub repo IOBR/IOBR@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                            
2: CRAN packages only             
3: None                           
4: stringi (1.5.3 -> 1.6.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
√  checking for file 'C:\Users\hp\AppData\Local\Temp\RtmpyGQ84Y\remotes256062c07413\IOBR-IOBR-769cbc5/DESCRIPTION' ...
-  preparing 'IOBR': (4.9s)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'IOBR_0.99.9.tar.gz'
   
Installing package into ‘D:/R/R-3.6.2/library’
(as ‘lib’ is unspecified)
* installing *source* package 'IOBR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'e1071'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'IOBR'
* removing 'D:/R/R-3.6.2/library/IOBR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/hp/AppData/Local/Temp/RtmpyGQ84Y/file256059794b2d/IOBR_0.99.9.tar.gz’ had non-zero exit status

**Comment by Byronxy** [comment]
there is no package called 'e1071', please install it firstly

**Comment by HelloMrScott** [comment]
I had the same question , and also install "e1071" first ,but it didn't work .please give a good help.
