### ISSUE TITLE
Error in validation.tbl_df(., !!.column, !!.row, !!.value)

### ISSUE THREAD

**Issue by huiyijiangling** [IOBR/IOBR#21]
``` R
res<-iobr_cor_plot(pdata_group           = pdata_group,
                   id1                   = "ID",
                   feature_data          = imvigor210_sig,
                   id2                   = "ID",
                   target                = "HCP5",
                   group                 = "group3",
                   is_target_continuous  = TRUE,
                   padj_cutoff           = 1,
                   index                 = 1,
                   category              = "signature",
                   signature_group       = sig_group,#[1:3],
                   ProjectID             = "IMvigor210",
                   palette_box           = "set2",
                   palette_corplot       = "pheatmap",
                   palette_heatmap       = 2,
                   feature_limit         = 26,
                   character_limit       = 30,
                   show_heatmap_col_name = FALSE,
                   show_col              = FALSE,
                   show_plot             = TRUE,
                   path                  = "3-HCP5-relevant-signatures")
```
Error in validation.tbl_df(., !!.column, !!.row, !!.value) : 
  tidyHeatmap says: Your dataset include duplicated row/column pairs. Please, remove redundancies before proceeding.
In addition: There were 50 or more warnings (use warnings() to see the first 50)

I have to change the "sig_group" to "sig_group[1:3]" to avoid errors. Thank you.
Thank you for the nice work your team have done.

**Comment by DongqiangZeng0808** [comment]
We set a parameter 'character_limit' to avoid the long names of features.
However, when some features with particularly similar names are selected to draw the heatmap at the same time, we should expand this parameter to avoid error reporting.

Please try the following code:
`res<-iobr_cor_plot(pdata_group           = pdata_group,
                   id1                   = "ID",
                   feature_data          = imvigor210_sig,
                   id2                   = "ID",
                   target                = "HCP5",
                   group                 = "group3",
                   is_target_continuous  = TRUE,
                   padj_cutoff           = 1,
                   index                 = 1,
                   category              = "signature",
                   signature_group       = sig_group,#[1:3],
                   ProjectID             = "IMvigor210",
                   palette_box           = "set2",
                   palette_corplot       = "pheatmap",
                   palette_heatmap       = 2,
                   feature_limit         = 26,
                   character_limit       = 60,
                   show_heatmap_col_name = FALSE,
                   show_col              = FALSE,
                   show_plot             = TRUE,
                   path                  = "3-HCP5-relevant-signatures")`

**Comment by liufuyan2016** [comment]
iobr_cor_plot could output the drawing text data?

**Comment by liufuyan2016** [comment]
There are another error:

Error in hclust(get_dist(submat, distance), method = method) :
  外接函数调用时不能有NA/NaN/Inf(arg10)
