### ISSUE TITLE
你好，请教一个问题

### ISSUE THREAD

**Issue by ranee123** [IOBR/IOBR#6]
你好，曾老师：
  我是南方医科大学一名在学生信的临床研究生，最近打算下载IOBR包运行，但是奈何不管网络，还是手动下载解压都无法加载到Rstudio里面？一直报错？百度谷歌不少答案，但也无法加载😫，想问下老师？谢谢

报错代码：
install.packages("C:/Users/Lenovo/Downloads/IOBR-master/IOBR-master/", repos = NULL, type = "source")
* installing *source* package 'IOBR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'tidyverse'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
停止执行
ERROR: lazy loading failed for package 'IOBR'
* removing 'D:/R-4.0.4/library/IOBR'
Warning in install.packages :
  installation of package ‘C:/Users/Lenovo/Downloads/IOBR-master/IOBR-master/’ had non-zero exit status

**Comment by Byronxy** [comment]
This error is due to the failure of installation of R package 'tidyverse'. Please try to install it firstly

**Comment by ranee123** [comment]
谢谢您
