### ISSUE TITLE
IOBR-xcell

### ISSUE THREAD

**Issue by ranee123** [IOBR/IOBR#8]
曾老师,你好:
   我最近在运行IOBR包的代码时候,发现遇到了一个报错问题,百度了也不知道为何?

麻烦你有空可以解答一下吗?
报错代码:
> xcell59733_log<-deconvo_tme(eset = eset_stad, method = "xcell", arrays =T)

>>> Running xCell
[1] "Num. of genes: 10796"
Error in .local(expr, gset.idx.list, ...) : 
  参数没有用(parallel.type = "SOCK")

不太懂它报错的是啥意思?

同时我输入了说明书文档里的代码,也出现了类似问题?
> library(IOBR)
> data("eset_stad")
> xcell<-deconvo_tme(eset = eset_stad, method = "xcell",arrays = FALSE)

>>> Running xCell
[1] "Num. of genes: 10761"
Error in .local(expr, gset.idx.list, ...) : 
  参数没有用(parallel.type = "SOCK")
> View(eset_stad)
> xcell<-deconvo_tme(eset = eset_stad, method = "xcell",arrays = FALSE)

>>> Running xCell
[1] "Num. of genes: 10761"
Error in .local(expr, gset.idx.list, ...) : 
  参数没有用(parallel.type = "SOCK")

**Comment by DongqiangZeng0808** [comment]
因为新版的GSVA包把这个参数给去掉了，已经更新，现在没问题了。
