### ISSUE TITLE
A small mistake in vignette 

### ISSUE THREAD

**Issue by longfei8533** [IOBR/IOBR#9]
https://iobr.github.io/IOBR/IOBR-VIGNETTE.html#Section.3.1
```
eset_stad$Ensembl_ID<-substring(eset_stad$Ensembl_ID, 1, 15)
eset_stad<-column_to_rownames(eset_stad, var = "Ensembl_ID")
# Revert back to original format because the data from UCSC was log2(x+1)transformed.
eset_stad<-(2^eset_stad)+1
```

 "eset_stad<-(2^eset_stad)+1" should to be  "eset_stad<-(2^eset_stad) - 1"

**Comment by DongqiangZeng0808** [comment]
Thank you for these observations. We have re-written this part and the vignette will be updated.
